name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  call-ci-job:
    uses: soorya-das/devops-workflow/.github/workflows/ci.yml@main
    with:
      pr-title: "^LIB-.*: .*"
      project-key: common-lib-service
      sonar-check-enabled: false
    secrets:
      github-token: ${{ secrets.MAVEN_PASSWORD }}
      github-username: ${{ secrets.MAVEN_USERNAME }}
